# Develop override settings

url: https://manufakturet-booking.github.io/   #url: http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
